import { Inter } from "next/font/google";
import "../globals.css";
import Image from "next/image";
import { getServerSession } from "next-auth";
import { redirect } from "next/navigation";
import Link from "next/link";

import { authOptions } from "../api/auth/[...nextauth]/route";
import { IoCaretBackCircle } from "react-icons/io5";
import AppSideLinks from "@/components/AppSideLinks";
import mongoose from "mongoose";
import Page from "@/models/Page";
import Header from "@/components/Header";
import { Toaster } from "react-hot-toast";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function AppLayout({ children }) {
  const session = await getServerSession(authOptions);
  mongoose.connect(process.env.MONGODB_URI);

  const page = await Page.findOne({
    owner: session?.user?.email,
  });

  if (!session) {
    return redirect("/");
  }

  return (
    <html lang="en">
      <body className={inter.className}>
        <Toaster />
        {page ? (
          <div className="flex h-screen">
            <aside className="p-4 h-full min-w-32 max-w-sm flex flex-col items-center  grow bg-white shadow-md">
              <div className="rounded-full overflow-hidden relative min-w-[126px] min-h-[126px]">
                <Image src={session?.user?.image} alt="avatar" fill />
              </div>
              <AppSideLinks />
              <Link
                className="flex  text-lg mt-auto mb-6 items-center gap-1 bg-blue-500 text-white py-2 px-4 rounded-lg "
                href={"/"}
              >
                <IoCaretBackCircle className="w-5 h-5" />
                Back to home
              </Link>
            </aside>
            <div className="py-6 px-12 grow-[4]">
              <div className="bg-white shadow text-2xl ">{children}</div>
            </div>
          </div>
        ) : (
          <div>
            <Header />
            {children}
          </div>
        )}
      </body>
    </html>
  );
}
